---
driver_config:
  digitalocean_client_id: <%= ENV['DIGITAL_OCEAN_CLIENT_ID'] %>
  digitalocean_api_key: <%= ENV['DIGITAL_OCEAN_API_KEY'] %>

provisioner:
  name: chef_zero
  require_chef_omnibus: latest

platforms:
  - name: ubuntu-1204
    driver_plugin: digitalocean
    driver_config:
      image_id: 3101045
      flavor_id: 63
      region_id: 4
      ssh_key_ids: <%= ENV['DIGITAL_OCEAN_SSH_KEY_IDS'] %>
      ssh_key: <%= ENV['DIGITAL_OCEAN_SSH_KEY_PATH'] %>
    run_list:
    - recipe[apt]
    attributes:
      apt:
        compile_time_update: true

suites:
  - name: default
    run_list:
      - recipe[database_restore::default]
      - recipe[database_restore::restore]
    attributes:
      mysql:
        server_root_password: 'rootpass'
        server_debian_password: 'debpass'
        server_repl_password: 'replpass'
      database_restore:
        s3_bucket: 'automagic-wordpress'
        s3_dir_path: 'backups/wordpressdb'
        database_backup_name: 'wordpressdb'
