AllCops:
  Excludes:
    - vendor/**
    - tmp/**

LineLength:
  Enabled: false
Documentation:
  Enabled: false
Encoding:
  Enabled: false
AlignHash:
  EnforcedHashRocketStyle: table
SingleSpaceBeforeFirstArg:
  Enabled: false
