language: ruby

rvm:
  - 2.1.0

bundler_args: --without development kitchen_vagrant
cache: bundler

before_script:
  - bundle exec berks install

script:
  # - bundle exec strainer test
  - bundle exec rake knife
  - bundle exec thor foodcritic:lint
